services:
  postgres_service_pomodoro:
    image: postgres:15.2-alpine
    env_file:
      - .dev.env
    container_name: postgres_services_pomodoro
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - "pgdata:/var/lib/postgresql/data"

  redis_service_pomodoro:
    image: redis:7-alpine
    container_name: redis_services_pomodoro
    restart: always
    ports:
      - "6379:6379"

volumes:
  pgdata: